# Generated by Django 4.1.2 on 2023-10-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_poster_url',
        ),
    ]
